import { Badge } from "@/components/ui/badge";
import { Sparkles, Clock, Shield } from "lucide-react";

interface AIExplanationProps {
  poolId: string;
}

export function AIExplanation({ poolId }: AIExplanationProps) {
  const explanation = `Today's NAV increased mainly because USD1 holdings in short-term U.S. Treasuries appreciated by 0.8%, and the pool accrued $12,304 in overnight interest. FX movements had a minimal impact, with EUR/USD fluctuating only 0.02% from yesterday's close. No large redemptions or subscriptions were recorded during this period.

The primary driver of today's positive movement was the continued compression of Treasury yields, which increased the mark-to-market value of the pool's fixed income holdings. The weighted average maturity of the portfolio remained stable at 45 days.`;

  return (
    <div className="glass-card p-6 animate-fade-in" style={{ animationDelay: "250ms" }}>
      <h3 className="text-lg font-semibold text-foreground mb-4">
        AI NAV Explanation
      </h3>

      <div className="flex items-center gap-3 mb-4 p-3 rounded-lg bg-secondary/10 border border-secondary/20">
        <div className="rounded-full bg-secondary/20 p-2">
          <Sparkles className="h-4 w-4 text-secondary" />
        </div>
        <div className="flex-1">
          <span className="text-sm font-medium text-foreground">
            Generated by NAV Coprocessor Agent
          </span>
          <div className="flex items-center gap-1 mt-0.5">
            <Clock className="h-3 w-3 text-muted-foreground" />
            <span className="text-xs text-muted-foreground">
              Updated 8 minutes ago
            </span>
          </div>
        </div>
      </div>

      <div className="prose prose-sm prose-invert max-w-none">
        <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">
          {explanation}
        </p>
      </div>

      <div className="flex items-center gap-2 mt-6 pt-4 border-t border-border/30">
        <Badge variant="success" className="gap-1">
          <Shield className="h-3 w-3" />
          Confidence: High
        </Badge>
        <Badge variant="muted">5 Data Sources</Badge>
      </div>
    </div>
  );
}
